#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
sudo sed -i '/server_name _;/a \\trewrite ^/redirect_me https:\/\/github.com\/Devjabli permanent;' /etc/nginx/sites-enabled/default
# Restarting Nginx service
sudo service nginx restart
