#!/usr/bin/env bash
# Script that shows 'To infinity and beyond' indefinitely In between each iteration of the loop, add a sleep 2

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
